### ISSUE TITLE
VR Video

### ISSUE THREAD

**Issue by galaxybeing** [myflashlab/GoogleVR-ANE#1]
Are you planing on implementing VR Video soon now that VR it is starting to heat up?  

I would like to create an app as a front end to my videos, a way to distribute them.  Or create a generic app that others can add their videos in a playlist and add an image for the "3D room" where the thumbnails reside.  It would be great to build it in Air.

**Comment by myflashlab** [comment]
Definitely! Keep checking back or sign up in our newsletter to know when it will be released.
