### ISSUE TITLE
own objects overlayed

### ISSUE THREAD

**Issue by painschen** [myflashlab/GoogleVR-ANE#10]
is it possible, to place movieclips in front of the image or video?

**Comment by myflashlab** [comment]
Nope that can't happen. The ANE is showing VR experience in a native window which is on top of AIR content.

**Comment by painschen** [comment]
so what is the embeed display mode for?

**Comment by myflashlab** [comment]
In future versions of the VR ANE, we are planing to make the VR window floatable over the AIR content instead of covering the whole screen. But even then, no AIR content can be placed over the VR content. That's the AIR rules!

**Comment by painschen** [comment]
Can you show me that AIR rule? Because my camera extension can be used embeed and i can overlay other objects (and i'm using additionally a modified barcode scanner to detect objects).. so it's like augmented reality.. why should AIR make that rule, if there are thousands ios apps supporting that? :o

**Comment by myflashlab** [comment]
That depends on how things are prepared. Maybe the camera extension you are talking about is parsing the images inside AIR. When that happens, you can of course overlay AIR content over it. On the VR case however, the native window is placed at the top of the AIR and no AIR content can be placed over it.
