### ISSUE TITLE
not able to compile in flash CC

### ISSUE THREAD

**Issue by ssshammi** [myflashlab/GoogleVR-ANE#11]
Hi can you please help me i tried to compile in flash css got this error.
Test Movie terminated.
The content cannot be loaded because there was a problem loading an extension: Error: Extension namespace is invalid for C:\Users\shammi\AppData\Local\Temp\Tmp_ANE_File_Unzipped_Packages\permissionCheck.ane
i changed the air sdk to 23.0 which is the latest.

**Comment by ssshammi** [comment]
Then i removed the permissiocheck.as and compiled, then i got this error. 
ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.myflashlab.air.extensions.googleVR::VRApi()
	at com.myflashlab.air.extensions.googleVR::VR()
	at com.myflashlab.air.extensions.googleVR::VR$/init()
	at Demo/init()[D:\shammi\GoogleVR-ANE-master\GoogleVR-ANE-master\FD\src\Demo.as:173]
	at Demo()[D:\shammi\GoogleVR-ANE-master\GoogleVR-ANE-master\FD\src\Demo.as:91]

**Comment by myflashlab** [comment]
You should also make sure it's changed in the AIR manifest file. take this manifest as an example and make sure yours is similar to this one: https://github.com/myflashlab/GoogleVR-ANE/blob/master/FD/application.xml

Yet, if you are trying to use the [PermissionCheck](https://github.com/myflashlab/PermissionCheck-ANE/) ANE, you should know that it is supported on AIR 24 or later only.

**Comment by myflashlab** [comment]
About your second question, the error message shows that you have not correctly embedded the ANE into your project, OR you are trying to run it on a simulator. Use a real device instead and you'll be fine. 

Make sure you are reading the documentation carefully before trying to test run the ANE. Besides that, we also have an inspector ANE which you may find very helpful when implementing our ANEs into your projects: https://github.com/myflashlab/ANE-Inspector-Tool This ANE will tell you what are you missing when implementing the ANE into you project.

**Comment by ssshammi** [comment]
![screenshot_20161120-200735](https://cloud.githubusercontent.com/assets/2300969/20463621/847a4576-af5d-11e6-93eb-471e1d6524ea.png)
![config](https://cloud.githubusercontent.com/assets/2300969/20463635/b3314f2c-af5d-11e6-9274-45fd0836e7ca.png)

Hi can you help me with this. its lot loading the 360 image what am i doing wrong when compiling in flash cc? and android setting. thanks

**Comment by myflashlab** [comment]
Are you sure you have correctly set the [manifest .xml](https://github.com/myflashlab/GoogleVR-ANE#air-xml-manifest) file? If so, please connect your device to your computer and watch the Android logcat to see what possible error messages are happening.

**Comment by myflashlab** [comment]
So, how's it going? feel free to drop us a line if you have more questions?
