### ISSUE TITLE
Deference MP4 VR quality play by other VR player?

### ISSUE THREAD

**Issue by iamSaravuth** [myflashlab/GoogleVR-ANE#12]
Why play by the same MP4 VR (top/bottom 3d 1920x1024 px) on this googleVR-ane (android) , the quality (resolution) less than (Blur)  from other VR player ?

**Comment by myflashlab** [comment]
With the ANE, we are just triggering native methods and have no control over how videos are decoded or played. you should probably ask this question on the native side so the Google team can comment on it. https://github.com/googlevr
