### ISSUE TITLE
Video view keep freezing at resolution > 1920x1920

### ISSUE THREAD

**Issue by rulyatmaja** [myflashlab/GoogleVR-ANE#13]
if i using common vr player something like AAA c*nema VR it can play for example at 2748 x 2748
but if using this plugin why i can just play at  1920 x1920, it's not  enough to play VR in clear/crisp image, if i using resolution 2500 x 2500 the video will freezing in 2 second after playing.. there is something wrong about buffering the video..
any clue?

**Comment by myflashlab** [comment]
Here's the official video specification that the Google VR supports:
https://developers.google.com/vr/concepts/vrview#video_specifications

Anyway, we are working on a newer version of the ANE to be released hopefully before 2017.

**Comment by rulyatmaja** [comment]
at that link it say it can use 2048 x 2048 video or higher but why i just can use 1920x 1920, my ohone is zenfone 2 memory 4GB. wonder why cant use higher resolution

**Comment by rulyatmaja** [comment]
at that link it say it can use 2048 x 2048 video or higher but why i just can use 1920x 1920, my ohone is zenfone 2 memory 4GB. wonder why cant use higher resolution

**Comment by rulyatmaja** [comment]
any clue in here can get better resolution than 1920?
since in google spec says " If maximum compatibility and quality is a priority, we recommend that users provide both a monoscopic 1920x1080 video and a stereo video at 2048x2048 or higher."

**Comment by rulyatmaja** [comment]
is Google VR common dependevieds is updating? since it always at version
0.9.1
and if i check google sdk newer version  is 1.4.0
may i request update for my purchased plugin?

**Comment by myflashlab** [comment]
We are working on an updated version. Will update this ticket as soon as it's completed.

**Comment by myflashlab** [comment]
Update yourself ti the latest version of the ANE. We are using the latest SDKs on both Android and iOS.
