### ISSUE TITLE
Dymamic content?

### ISSUE THREAD

**Issue by Nikos-Laskaridis** [myflashlab/GoogleVR-ANE#14]
Is it possible to have dynamic content instead of image file? I wish to make an Augmented reality VR app that will combine camera image and movieclips. Maybe if I render these consnatly to a single bitmap?

**Comment by myflashlab** [comment]
I'm not sure. with the ANE in AIR, we could only support 360 images and videos but for interactive content, you could use the native libraries. the current native OpenGL SDK used in the native SDKs can't be ported to AS3. That's why we are supporting the photo/video options only.
