### ISSUE TITLE
googleVR.ane is not a valid native extension file

### ISSUE THREAD

**Issue by Akali65** [myflashlab/GoogleVR-ANE#15]
Hi

I want to purchase the googleVR.ane and have got it to work on my Android device without a problem. However, I cannot compile an iOS version and want to make sure it works on iPhone before purchase. 

When I compile the iOS version I keep getting the error 'googleVR.ane is not a valid native extension file'. (See image).

I am using Adobe Animate, AIR SDK 24.0.0.180 for iOS and have added the googleVR.ane and the permissionCheck.ane and used the .xml settings (I've uploaded this as a .txt file below). I have placed the following next to the main .swf of my project CardboardSDK.bundle, GoogleKitCore.bundle, GoogleKitDialogs.bundle, GoogleKitHUD.bundle and MaterialRobotoFontLoader.bundle. 

Can you help me resolve the problem please? This is great product by the way and I am hoping you can help me to get it to work on iOS.

![iosproblem](https://cloud.githubusercontent.com/assets/24958799/21718585/496ed136-d410-11e6-921a-91af61d9d72e.png)

[Dem1iOS-app.txt](https://github.com/myflashlab/GoogleVR-ANE/files/690519/Dem1iOS-app.txt)

**Comment by Akali65** [comment]
Just an update. I can compile and run the GoogleVR.ane when using Air 23.0 on iOS. The problem I've explained above arises when using Air24.0.0.180.

**Comment by myflashlab** [comment]
It seems like AIR 24 is somehow buggy as mentioned in this forum on Adobe: https://forums.adobe.com/thread/2234443#access_token=eyJ4NXUiOiJpbXNfbmExLWtleS0xLmNlciIsImFsZyI6IlJTMjU2In0.eyJmZyI6IlJDTzdZV0hISElBQUFBQUFBQUFBQUFGM0FBPT09PT09IiwiYXMiOiJpbXMtbmExIiwiYyI6IkZBWmVLNm9rUE50dUNSSm12UnZUYkE9PSIsInVzZXJfaWQiOiI1MjA5NjdBRTQ2OUNDMzhCOTkyMDE1QThAQWRvYmVJRCIsIm1vaSI6IjJhNmQ4NGRiIiwic2NvcGUiOiJBZG9iZUlELG9wZW5pZCxhZGRpdGlvbmFsX2luZm8uc2NyZWVuX25hbWUsdXBkYXRlX3Byb2ZpbGUuc2NyZWVuX25hbWUiLCJjcmVhdGVkX2F0IjoiMTQ4Mzg4NTIzMDYyMSIsImlkIjoiMTQ4Mzg4NTIzMDYyMS05NTFhOGVjMy0yYjE5LTQwMjktYjk5NC0zZTU3NTk3MDIzYjkiLCJzdGF0ZSI6IiIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJleHBpcmVzX2luIjoiODY0MDAwMDAiLCJjbGllbnRfaWQiOiJmb3J1bXMyIn0.Ap5EcydWTUVjgJKQRb2edA1NnQIl_8O6NBYkiDmsx_S_N4bSB3SFtYQ8sO-Ylqmfma7iHc89eOIdyHNOV_JLV-SwgobHQTX_GteWCrLpWVISZCCcBbAup5ZPCi8B_d3cp8_wOF0Hykur6YO5oPqb8Yfsg96lglDepUdHHgmNygJFPluqWmiIts9--457A8s3c9F33zfevmT0xDPL9fq-_eK9oLfqp8dTjnxReSk1S8eNMPDDMhryYKl4VsXcmxLghP6EUXYlk0U1axyWn7NTklj8UrbRauyz8sL_RPWcZEM_5SOW_POyHnv8O778KjdEMzp96AoxOAUOSmnytGugHA&token_type=bearer&expires_in=86399991

However, we'll have a closer look at this and let you know. we had tested the ANE with AIR 24-beta and worked fine. We'll test it with AIR 24-180 to see how it goes.

**Comment by myflashlab** [comment]
We just updated the ANE to V2.1.1 and it works fine on AIR 24 also.
