### ISSUE TITLE
possible for us to put in subtitle(load from a external file) to the video

### ISSUE THREAD

**Issue by hengway1989** [myflashlab/GoogleVR-ANE#16]
Hi, can I know any possibility for us to load a external subtitle file and display in the VR? Thank you

Example:
![whatsapp image 2017-01-23 at 12 10 55](https://cloud.githubusercontent.com/assets/13148479/22197152/4836b362-e183-11e6-80bd-9817e668474b.jpeg)

**Comment by myflashlab** [comment]
For custom works, please contact us through http://www.myflashlabs.com/contact/
