### ISSUE TITLE
Possible to overlay graphics on the video?

### ISSUE THREAD

**Issue by SeanJD** [myflashlab/GoogleVR-ANE#17]
Hi
I've got a use-case for this which asks for me to be able to add graphical elements on top of the video layer. The video doesn't necessarily have to be playing at the time but it does need to have the 360 motion.
Is it any way possible to add a display list above the playing video or is it in a completely separate container to the rest of the AIR app? 
i.e. can we add a custom UI over the top of the video layer whilst playing or paused?

Thanks

**Comment by myflashlab** [comment]
No, sorry. That is not possible. you cannot draw AIR content over a native window. If you need a custom UI over the native content, you need to do that on the native side.
