### ISSUE TITLE
cant play big size video

### ISSUE THREAD

**Issue by rulyatmaja** [myflashlab/GoogleVR-ANE#18]
i use 1920 x 1920 resolution,, try 15 minutes video about 800MB file it freezing or stuck ,, use ordinary playstore VR Player.. the same video played like a charm,, using ordinary VR player on playstore can play more than 1.5 GB Video File size.. with air app and this plugin just can play about 300mb video ..  largeheap = true is done, any clue how play more size video?

**Comment by rulyatmaja** [comment]
may be the problem is GVR common dependencies. it is version is 0.9.1 and current GVR SDK is 1.4.0, will it update soon?

**Comment by myflashlab** [comment]
We have just released a newer version with the latest version of GVR SDK for both Android and iOS, please try your content with the latest ANE and see how it goes.
