### ISSUE TITLE
Setting DisplayMode to FULLSCREEN_STEREO as default

### ISSUE THREAD

**Issue by sairope** [myflashlab/GoogleVR-ANE#19]
Is there any way to make FULLSCREEN_STEREO as default DisplayMode. Whenever I tap to change a photo withing the VR View my image is loaded in the EMBEDDED mode. Is there any way to change it? Any workaround? I haven't found anything in your documentation, but it definitely can be done natively.

**Comment by eugenefish** [comment]
Hi there, I have found this code, and enabled it, however when this line triggers, the app bombs.
VR.api.displayMode = DisplayMode.FULLSCREEN_STEREO;

Is there anything else we need to do? Do you know about the app bombing when this is triggered?

**Comment by myflashlab** [comment]
```VR.api.displayMode = DisplayMode.FULLSCREEN_STEREO;``` can be called for example when content is ready. call that method when ```VREvents.LOAD_SUCCESS``` occurs.

```actionscript
VR.api.imageView.addEventListener(VREvents.LOAD_SUCCESS, onLoadSuccess);
VR.api.videoView.addEventListener(VREvents.LOAD_SUCCESS, onVideoLoadSuccess);
```
