### ISSUE TITLE
ArgumentError: Error #3500:  googleVR-ANE 

### ISSUE THREAD

**Issue by iamSaravuth** [myflashlab/GoogleVR-ANE#2]
i use FlashIDE to develop my project after export error message.
ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.myflashlab.air.extensions.googleVR::ApiVideoView/attach()

How to fix it.

**Comment by myflashlab** [comment]
This error means that the ANE can't run. It's either because you are trying to run on a simulator or the ANE has not been correctly embedded in your project. If you need to be sure what the problem could be exactly, you may use our free [ANE inspector tool](https://github.com/myflashlab/ANE-Inspector-Tool).

**Comment by iamSaravuth** [comment]
Thanks for your suggest. I try embed ANE-Inspector-Tool  return Inspector.lastError = This ANE cannot run on a simulator. There might be other problems too but the first thing to do is to test your app on a real device. I try public APK (https://drive.google.com/file/d/0B-VyEYQH4jttSlpKVndGZm1xWEE/view?usp=sharing) and test on my device but noting run. May you can sample (.fla) to me. Thanks you.

**Comment by myflashlab** [comment]
After having a look at your manifest .xml file, I noticed that you have not added the required setting in the manifest. Please read here to see what changes you need to make: https://github.com/myflashlab/GoogleVR-ANE#air-xml-manifest

Hint: If you are using FlashCC/Animate  IDE, you need to make sure the IDE is not automatically changing your settings. You may find this video helpful: https://www.youtube.com/watch?v=fhtZw5ZDFMs

**Comment by myflashlab** [comment]
Please let us know how things go, If you have more questions, feel free to ask.

**Comment by iamSaravuth** [comment]
Dear Support,

 

Thank you for suggest but I have some question.

 

1.       How to skip google glass setting  after tab TYPE STEREO (No need to show).

2.       How to force “videoType”  to  STEREO and FULLSCREEN on start application  

 

 

Saravuth L.

**Comment by myflashlab** [comment]
> How to skip google glass setting after tab TYPE STEREO (No need to show).
How to force “videoType” to STEREO and FULLSCREEN on start application

You can't the animation and setting page is designed inside the SDK by Google. If in future they allow us to control that, we will build that too but for now, it's all there by default.
