### ISSUE TITLE
Does it possible to get coordinates on DID_TAP?

### ISSUE THREAD

**Issue by stasks** [myflashlab/GoogleVR-ANE#20]
In image 360 view I need to get finger tap coordinates, how can I do this? Not headPosition, but tap coordinates regarding image.

Thanks,

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
