### ISSUE TITLE
iOS application crashes after VR.api.imageView.attach()

### ISSUE THREAD

**Issue by mrenninger** [myflashlab/GoogleVR-ANE#21]
Has anyone experienced this?

The app is dependent on Starling 1.7 and Starling's Asset Manager.  Is the ImageView possibly incompatible with Textures?

* MacOS 10.12.4, IntelliJ IDEA 2017.1, compiling AIR 25 to iOS 10.3.1

**Comment by mrenninger** [comment]
Looks like it happens in the demo as well.  Tested on an iPhone 6 and 7Plus both running iOS 10.3.1.

**Comment by myflashlab** [comment]
First of all, update to the latest version which includes the latest VR SDK for both Android/iOS. Second of all, always remember that on iOS, if you are using Starling (or any other content which uses the OpenGL) you need to stop/freeze your content before you can start the VR experience. Try that and it will work fine. (Android is able to work even if you don't stop your OpenGL content but still it is a good idea to freeze starling when you start VR and resume when you come back.

**Comment by mrenninger** [comment]
Hi again - I pulled the newest version of the GoogleVR ANE, updated all of the required dependencies, frameworks and bundles and, though the demo project no longer crashes, now I get a black screen once VR.api.imageView.attach() is called.  Is there an updated version of the demo project that I can try out?  Also, How do I restore my ANE to the purchased version?

**Comment by mrenninger** [comment]
Please note that I'm doing my tests on the demo project for now to avoid using Starling.

**Comment by myflashlab** [comment]
Good to know it worked fine.

> How do I restore my ANE to the purchased version (I purchased 2 weeks ago)?

Just login to your myflashlabs.com account and grab your licensed ANE from there.
