### ISSUE TITLE
Does it possible to show an displayobject over the video?

### ISSUE THREAD

**Issue by aopar75** [myflashlab/GoogleVR-ANE#23]
There is a way to display a displayObject (sprite, movieclip) covering the video?

Thanks.

**Comment by aopar75** [comment]
Sorry, already response on closed threads.

**Comment by peteshand** [comment]
I'm also interested in this. Presumably it's not really possible (or at least will be difficult to implement) due to the fact that the the 360 Image/Video is being rendered in OpenGL. 

Maybe an alternative would be to simply provide additional headRotation data so the end as3 user could used this data and render content with a stage3d library. 

There is already VR.api.headRotation, however it appears there are only two values, rotationX and rotationY, so an extra rotationZ would be required and it also appears that VR.api.headRotation is only accessible if an Image/Video is being display?

**Comment by myflashlab** [comment]
@peteshand What you suggested seems to make good sense. Will you be able to help let us know what features from the original SDK can help you achieve something like what you suggested in Stage3d? start by looking at this: https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/package-summary

Tell us if this information is useful to you? and if so, tell us how do you want to have access to them in AIR. maybe we can improve the ANE with them?

Thanks for your cooperation.

**Comment by peteshand** [comment]
Hey there
Yeah so I think it would be as simple as exposing the values in HeadTransform: https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/HeadTransform

void | getEulerAngles(float[] eulerAngles, int offset)
void | getForwardVector(float[] forward, int offset)
void | getHeadView(float[] headView, int offset)
void | getQuaternion(float[] quaternion, int offset)
void | getRightVector(float[] right, int offset)
void | getTranslation(float[] translation, int offset)
void | getUpVector(float[] up, int offset)

**Comment by myflashlab** [comment]
Well, We are very interested in this. If you have been following us recently, you might know that we are working on an AR ANE release soon. And besides that, we are working on a new LocalNotifi and beacon ANE. We want to provide AIR with a full package relate to Virtual and Augmented reality tools. And now, we are interested in your suggestion and want to make it happen.

@peteshand to be fast on this, we need your help. We have already too much in our plate and if you can help us with some time, we would appreciate it. To compensate your time, we'd be happy to offer you a big discount on our Club membership. (The club membership will soon have AR, Beacon, LocalNitifi, the updated VR and many more).

So, we require a sample Stage3d class similar to treasure hunt demo which Google has for example here: https://github.com/googlevr/gvr-android-sdk/tree/master/samples So we can use it while developing the ANE. This would help us with the 3D Audio thing also. If you are interested, drop us an email through http://www.myflashlabs.com/contact/
