### ISSUE TITLE
Animate sample

### ISSUE THREAD

**Issue by vostemani** [myflashlab/GoogleVR-ANE#25]
Hi. Anyone have an Adobe Animate sample using this ANE? Thanks!!!

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
