### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by allanwcox** [myflashlab/GoogleVR-ANE#3]
The 360 Video has vrSetting.video360URL to load videos from a URL. Can you add vrSetting.image360URL so I can load 360 images from a URL. Is it possible to control the size (height / width) of the image, video and back button? Then could I control the location of the image, video and back button?

**Comment by myflashlab** [comment]
well, adding a method like ```image360URL``` is unnecessary. Because you can simply load the image with any other tool, put it in the storage then load it by the VR ANE.

As far as features, we are mainly exposing what Google has provided to us. https://developers.google.com/vr/android/release-notes
