### ISSUE TITLE
GoogleVR ANE "cursor" not appearing, is it possibe?

### ISSUE THREAD

**Issue by mmoro** [myflashlab/GoogleVR-ANE#30]
## Environment ##
ALL iOS and Android.

## Problem Description ##
we have developed iOS and Android VR Apps using your GoogleVR ANE, and found out there's one item that would be a great thing to have, and it's the "cursor"/"pointer" to select an element. On the screenshot attached you will see we have video thumbnail in place, but it doesn't have a dot "cursor" to make sure you are selecting that item. We have seen some other VR Apps using it and it`s a much better UX. 

## Steps to Reproduce ##
by using the Google VR ANE and selecting thumnails from a 360 menu. 

Thanks!
Mariano
![vr cursor do not appear](https://user-images.githubusercontent.com/7967910/40786629-dd7d83fc-64c1-11e8-98bf-12ddd7b157fb.png)

**Comment by myflashlab** [comment]
VR on AIR is limited to 360 videos and photos. there can't be much interaction with the VR world. I don't think we could do that at all but we'll look into this with more focus when we are updating the ANE with the latest SDK version changes.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
