### ISSUE TITLE
Google VR ANE - 360 video reproduction issues

### ISSUE THREAD

**Issue by mmoro** [myflashlab/GoogleVR-ANE#31]
Hello Team-

we are using the latest version of the Google VR ANE and it´s failing on Android while reproducing 360 videos. 

Issue description; https://www.youtube.com/watch?v=8jtdKTRNt7w&feature=youtu.be 

1) after several attempts, and while seeing the video in stereo the image goes black, but the sound still reproducing.
2) from the code there´s no way to put the video in Stereo mode, like we do iOS. 
3) from time to time, while reproducing a 360 video, the app crashes. 

Thanks and look forward to hearing asap. we are on a real hurry with it. 
Mariano

**Comment by myflashlab** [comment]
Thanks for the video presentation. I wonder if this happens on all your devices? the Android version you're using seems to be an old one.

Anyhow, Google VR library has been changed drastically lately and deprecated some of the older libraries that we had used for creating the ANE; And it has forced us to do almost a complete redo of the ANE. we have this task on our to-do list and trying to find a time to complete it.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
