### ISSUE TITLE
On iOS - No Google VR Cardboard option available for video in EMBEDDED view

### ISSUE THREAD

**Issue by mc3dev** [myflashlab/GoogleVR-ANE#6]
Hi, 

I was able to use Animate to get the Demo working in AIR for iOS. It can open the 360 video. However, it's showing the mono view only,  there is no Google cardboard viewer icon available even through the seteroModeButtonEnabled is set to true. The option is available on the 360 image view though.

It appears that the seteroModeButton is under the video control bar. Is that true? If so, how can I make the steroModeButton positioned higher so it does not get covered by the video control without setting it to fullscreen mode?

Can you provide any feedback on this issue? Thanks in advance.

**Comment by myflashlab** [comment]
Thanks for reporting this. We will fix the problem in the next release.
