### ISSUE TITLE
On iOS - No way to turn off the "i" info button in Fullscreen view

### ISSUE THREAD

**Issue by mc3dev** [myflashlab/GoogleVR-ANE#7]
Hi,

On iOS, when infoButtonEnabled is set to false, it is still showing on the fullscreen view. 
How can it be turned off? Please advise. Thank you much.

**Comment by myflashlab** [comment]
Unlike the Android SDK, Google is not yet supporting an option to remove the (i) button on the iOS side. We're sure they will soon add that. When they do, we'll update the ANE too.

**Comment by painschen** [comment]
is it possible to change the target of the i-button?

**Comment by myflashlab** [comment]
Google is not providing us this feature right now.

**Comment by painschen** [comment]
i'm wondering, because in the web sdk (vr view) its easy to change.. hope you'll find a solution soon!

<a id="watermark" href="http://g.co/vr/view" target="_blank">
      <img src="images/ic_info_outline_black_24dp.svg"/>
    </a>

**Comment by myflashlab** [comment]
Update to the latest version of the ANE and this feature will also work for the iOS side.
